style: github
template: CHANGELOG.tpl.md
info:
    title: CHANGELOG
    repository_url: https://github.com/BombenProdukt/zai
options:
    commits:
        filters:
            Type:
                - feat
                - fix
                - perf
                - refactor
    commit_groups:
        title_maps:
            feat: Added
            fix: Fixed
            perf: Changed
            refactor: Changed
    header:
        pattern: "^(\\w*)\\:\\s(.*)$"
        pattern_maps:
            - Type
            - Subject
    notes:
        keywords:
            - BREAKING CHANGE
